//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDH
    {
        public int Soluong { get; set; }
        public int Dongia { get; set; }
        public int ThanhTien { get; set; }
        public int MaDH { get; set; }
        public int MaSP { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
